openapi: 3.0.1
info:
  title: Camapign studio Slooce Transport bundle plugin
  description: Plugin to provide Slooce transport to Campaign Studio
  x-cortex-tag: acquia/mc-cs-plugin-slooce
  x-cortex-git:
    github:
      repository: acquia/mc-cs-plugin-slooce
  x-cortex-owners:
    - type: GROUP
      name: acquia/mc-cs-team
      provider: GITHUB
      description: This team is responsible for development and code review of campaign studio related PRs
    - type: SLACK
      channel: mc-csf-engineering
      notificationsEnabled: true
      description: This channel is used for notify updates, team help, technical discussions
  x-cortex-groups:
    - marketing-cloud
    - is-service
    - has-api
    - has-frontend
