<?php
/*
 * @copyright   2018 Mautic Contributors. All rights reserved
 * @author      Mautic
 *
 * @link        http://mautic.org
 *
 * @license     GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 * @author      Jan Kozak <galvani78@gmail.com>
 */

namespace MauticPlugin\MauticSlooceTransportBundle\Tests\Slooce;

use MauticPlugin\MauticSlooceTransportBundle\Message\MessageFactory;
use MauticPlugin\MauticSlooceTransportBundle\Slooce\Connector;

class ConnectorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Connector
     */
    private $connector;

    public function setUp()
    {
        $this->connector = new Connector();
        $this->connector
            ->setPassword('borg')
            ->setPartnerId('number7')
            ->setSlooceDomain('universe')
            ->setShortCodeField('scfi')
            ;


        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetShortCodeField()
    {
        $this->assertEquals('scfi', $this->connector->getShortCodeField());
    }
}
