<?php
/*
 * @copyright   2018 Mautic Contributors. All rights reserved
 * @author      Mautic
 *
 * @link        http://mautic.org
 *
 * @license     GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 * @author      Jan Kozak <galvani78@gmail.com>
 */

namespace MauticPlugin\MauticSlooceTransportBundle\Tests\Transport;

use MauticPlugin\MauticSlooceTransportBundle\Message\MtMessage;
use MauticPlugin\MauticSlooceTransportBundle\Slooce\Connector;
use MauticPlugin\MauticSlooceTransportBundle\Transport\SlooceTransport;

class SlooceTransportTest extends \PHPUnit_Framework_TestCase
{
    /** @var Connector */
    private $connector;

    /** @var MtMessage */
    private $message;

    public function setUp()
    {
        $this->connector = $this->createMock(Connector::class);
        $this->connector->expects($this->any())->method('sendMtMessage')->will($this->returnValue(['status'=>true]));

        $this->message = new MtMessage('test-message');
        $this->message->setContent('restistance is futile');

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testSendSms()
    {

    }
}
