<?php

namespace MauticPlugin\MauticSlooceTransportBundle\Tests\Transport;

use MauticPlugin\MauticSlooceTransportBundle\Message\MtMessage;
use MauticPlugin\MauticSlooceTransportBundle\Slooce\Connector;

class SlooceTransportTest extends \PHPUnit\Framework\TestCase
{
    /** @var Connector */
    private $connector;

    /** @var MtMessage */
    private $message;

    protected function setUp(): void
    {
        $this->connector = $this->createMock(Connector::class);
        $this->connector->expects($this->any())->method('sendMtMessage')->will($this->returnValue(['status'=>true]));

        $this->message = new MtMessage('test-message');
        $this->message->setContent('restistance is futile');

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testSendSms()
    {
        $this->markTestSkipped(/** @todo */);
    }
}
